SELECT 
    USERNAME
FROM
    (SELECT 
        USERNAME, COUNT(USER.USER_ID) AMOUNT
    FROM
        Discountropium.OFFER
    LEFT JOIN Discountropium.USER ON OFFER.USER_ID = USER.USER_ID
    WHERE
        DATE(OFFER.CREATED_AT) >= CURDATE() - 10
            AND VENDOR = TRUE
    GROUP BY OFFER.USER_ID) AS OFFERS_FOR_USER
WHERE
    AMOUNT > 3