SELECT 
    IFNULL(MAS_AMOUNT.AMOUNT, 0) AS AMOUNT, USER.USERNAME
FROM
    Discountropium.USER
        LEFT JOIN
    (SELECT 
        REVIEWS.USERNAME,
            REVIEWS.REVIEW_DATE,
            COUNT(*) AMOUNT
    FROM
        Discountropium.REVIEWS
    WHERE
        REVIEWS.REVIEW_DATE = '2021-05-09'
    GROUP BY REVIEWS.USERNAME) AS MAS_AMOUNT ON USER.USERNAME = MAS_AMOUNT.USERNAME
    
