SELECT 
    *, REWIEWS_RATE.AVGS
FROM
    Discountropium.OFFER
        LEFT JOIN
    (SELECT 
        REVIEWS.OFFER_ID, AVG(REVIEWS.RATE) AVGS
    FROM
        REVIEWS
    GROUP BY REVIEWS.OFFER_ID) AS REWIEWS_RATE ON OFFER.OFFER_ID = REWIEWS_RATE.OFFER_ID
WHERE
    AVGS > 3