SELECT 
    *
FROM
    Discountropium.OFFER
        LEFT JOIN
    (SELECT 
        REVIEWS.OFFER_ID, COUNT(*) REVIEWSN
    FROM
        REVIEWS
    GROUP BY REVIEWS.OFFER_ID) AS REWIEWSN ON OFFER.OFFER_ID = REWIEWSN.OFFER_ID
WHERE
    REVIEWSN > 3